version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: "Install Packages"
          command: |
            npm install
      - run:
          name: "Build and Test"
          command: |
            npm run test
workflows:
  version: 2
  buildAndTest:
    jobs:
      - test


